# wso2mi-deployment-car.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wso2mi-deployment
  labels:
    app: wso2mi
spec:
  replicas: 1 # Initial replica count, HPA will manage this
  selector:
    matchLabels:
      app: wso2mi
  template:
    metadata:
      labels:
        app: wso2mi
    spec:
      containers:
      - name: wso2mi-container
        # IMPORTANT: Replace with the custom image you built
        image: wso2mi-w-cars:latest
        imagePullPolicy: IfNotPresent # Or Always, if you push to a remote registry and update frequently
        ports:
        - containerPort: 8290 # HTTP transport
        - containerPort: 8253 # HTTPS transport
        - containerPort: 9164 # Management HTTPS port
        env:
        - name: BACKEND_DELAY # Environment variable to control latency in your API
          value: "5000" # Default latency, your FastAPI app will update this
        # Define resource requests and limits for HPA to work effectively
        resources:
          requests:
            memory: "2Gi" # Adjust as needed
            cpu: "1"     # Adjust as needed
          limits:
            memory: "2Gi"   # Adjust as needed
            cpu: "1"        # Adjust as needed
        # Readiness and Liveness probes for MI
        # Ensure the API context /latencyPassThrough/ is correct
        readinessProbe:
          httpGet:
            path: /healthz
            port: 9201
          initialDelaySeconds: 60 # MI + CAR deployment can take time
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 10 # Allow more failures during initial CAR deployment
        livenessProbe:
          tcpSocket:
            port: 8290
          initialDelaySeconds: 120
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 5
---
# wso2mi-service-car.yaml (This can remain the same as before)
apiVersion: v1
kind: Service
metadata:
  name: wso2mi-service
  labels:
    app: wso2mi
spec:
  selector:
    app: wso2mi # Must match the labels of the wso2mi Deployment's pods
  ports:
  - name: http
    protocol: TCP
    port: 8290
    targetPort: 8290
  - name: https
    protocol: TCP
    port: 8253
    targetPort: 8253
  type: LoadBalancer
---
# wso2mi-hpa-aggressive.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: wso2mi-hpa # Should match the existing HPA name to update it
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: wso2mi-deployment # Must match the name of your MI Deployment
  minReplicas: 1
  maxReplicas: 5 # Increased max replicas for a better scaling demo range
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        # Target 50% CPU utilization before scaling up.
        # This value might need adjustment based on typical MI load.
        averageUtilization: 50
  behavior:
    scaleDown:
      # Stabilization window for scaling down.
      # Shorter window means faster scale-down reaction.
      # Default is 300 seconds (5 minutes).
      stabilizationWindowSeconds: 90 # Reduced to 90 seconds (1.5 minutes)
      policies:
      # Allow scaling down by a larger number of pods or percentage more quickly.
      - type: Pods
        value: 2 # Allow removing up to 2 pods at a time during scale down
        periodSeconds: 30 # Check every 30 seconds for scale down opportunities
      - type: Percent
        value: 50 # Allow removing up to 50% of current pods (respecting minReplicas)
        periodSeconds: 60 # Check every 60 seconds
      # selectPolicy: Max # Default is Max, meaning it will take the more aggressive policy
    scaleUp:
      # Stabilization window for scaling up.
      # 0 means scale up as soon as metrics are met.
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent # Allow adding a significant percentage of pods
        value: 100 # Allow doubling the number of pods (up to maxReplicas)
        periodSeconds: 15 # Check every 15 seconds for scale up
      - type: Pods # Also allow adding a fixed number of pods quickly
        value: 3 # Allow adding up to 3 pods at a time
        periodSeconds: 15
      selectPolicy: Max # Take the action that adds more pods
